[package]
name = "my_r_efi_kernel"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
uefi = { version = "0.35.0", default-features = false}
uefi-raw = "0.11.0"
x86_64 = { version = "0.15.2", default-features = false, features = ["instructions"] }
