[build]
target = "i386-unknown-none.json"

[target.'cfg(any())']
# This tells Cargo to use your custom linker script automatically
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
]

[unstable]
build-std = ["core"]
